### ISSUE TITLE
Extract UserInterface

### ISSUE THREAD

**Issue by b3nl** [commercetools/commercetools-php-symfony#27]
The written AuthenticationProvider is compatible with different "user bundles" like the one from fos. But, we can not use our own implementation for a user, because the real implementation, instead of an interface (which could contain the cart api etc.), of the commercetools user class is checked.

```php            
            if ($user instanceof User) {
                $user->setId($customer->getId());
                $cart = $result->getCart();
                if (!is_null($cart)) {
                    $user->setCartId($cart->getId());
                    $user->setCartItemCount($cart->getLineItemCount());
                }
            }
``` 

Please extract the added user api to an interface and check against this interface.

**Comment by jayS-de** [comment]
I just extracted the user class to an Interface and changed the checked to the interface.

Would be nice if you could check if this is working using the develop branch
